name: Build Electron App (Linux + Mac)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build macOS App
        run: npx electron-builder --mac

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-mac
          path: dist/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Install Linux build tools
        run: sudo apt update && sudo apt install -y fakeroot dpkg-dev rpm

      - name: Build Linux App
        run: npx electron-builder --linux

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-linux
          path: dist/
